site_name: NPS Hikes
site_description: Personal project by Sean Angiolillo for collecting, analyzing, and exploring US National Park hiking trail data.
site_author: Sean Angiolillo
site_url: https://seanangio.github.io/nps-hikes/
repo_url: https://github.com/seanangio/nps-hikes

theme:
  name: material
  favicon: assets/boot.png
  logo: assets/boot.png
  features:
    - content.code.copy
    - navigation.instant
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - footnotes

extra:
  analytics:
    provider: google
    property: G-9X7X15048G

nav:
  - Home: index.md
  - getting-started.md
  - data.md
  - api-tutorial.md
